### PR TITLE
HTML images with numbered id attributes

### PR DESCRIPTION
**Pull request by lmmx**
Numbered images in the ID attributes, so you can link to individual slides. Processed with https://gist.github.com/lmmx/860690d3430c7715dfac

### CODE REVIEW

**Comment by lmmx** [comment]
Happy to do this for the other talks in the repo if you'd like, or I'll just use the copy in my branch if you want to stick with HTML-free markdown in yours, I was in the midst of transcribing the talk when I found you already had :smile:

**Comment by matthiasn** [comment]
Thanks, I like the idea, I just wonder if there is a way to do this with the location hash so the link leads to the slide in context with the surrounding text. When I talked to Rich Hickey at the Conj, he said he really liked that the slides were only presented in context with what was said at the presentation, so would like to make sure it stays that way.

**Comment by lmmx** [comment]
I don't follow... the link goes to the slide (the image), positioning the page with the image at the top so it's shown in full, and its corresponding text below:

> [e.g. slide 27](https://github.com/lmmx/talk-transcripts/blob/master/Hickey_Rich/AreWeThereYet.md#user-content-slide-27): the text below the image is the first reference to the slide's text.

Context is there just... by observing where the scrollbar is, surely? I get that you wouldn't want people to jump into a presentation at certain slides, but this numbering allows for specific attribution within a talk. I mean, numbering pages in a book doesn't carry the danger of it being taken out of context, it's just sensible for work of any significant length.

Personally I'm referencing specific slides in a blog post and wanted to concisely both refer and link to slides as I mention their content (otherwise I am essentially not giving context).

I wouldn't expect RH to have a problem with it, but then again I'm not the one who's met him! Your call :+1:

**Comment by matthiasn** [comment]
Weird, when I clicked on the "slide 8" link earlier, it sent me directly to the image without any surrounding text. Whatever, now it is behaving exactly as I would expect it to. I've merged the PR, please feel free to do the same for other talks. Thanks!

**Comment by lmmx** [comment]
Brill, will do! :grinning:

**Pull request merged**
